# Generated by Django 3.1.5 on 2021-01-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_id', models.FloatField(max_length=200, null=True)),
                ('product_id', models.FloatField(max_length=200, null=True)),
                ('sku_name', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=50)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('salt_name', models.CharField(max_length=200)),
                ('drug_form', models.CharField(max_length=50)),
                ('pack_size', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=200, null=True)),
                ('product_banned_flag', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('price_per_unit', models.FloatField(max_length=200)),
                ('catalogue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.catalogue')),
            ],
        ),
    ]
