# Generated by Django 3.1.5 on 2021-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='sku_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
