# Generated by Django 3.1.5 on 2021-01-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20210126_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price_per_unit',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.IntegerField(null=True),
        ),
    ]
