# Generated by Django 3.1.5 on 2021-01-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20210126_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'managed': False},
        ),
    ]
