# Generated by Django 3.1.5 on 2021-01-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20210126_1340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogue',
            table='Catalogues',
        ),
    ]
