# Generated by Django 3.1.5 on 2021-01-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20210126_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={},
        ),
    ]
