# Generated by Django 3.1.5 on 2021-01-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_auto_20210126_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='catalogue_id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='catalogue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicine.catalogue'),
            preserve_default=False,
        ),
    ]
